[tool.poetry]
name = "pycouchdb"
version = "1.14.1"
description = "Modern pure python CouchDB Client."
authors = ["Andrey Antukh <niwi@niwi.be>"]
maintainers = ["Rinat Sabitov <rinat.sabitov@gmail.com>"]
license = "BSD-4-Clause"
readme = "README.md"
repository = "https://github.com/histrio/py-couchdb"
documentation = "https://pycouchdb.readthedocs.io/en/latest/"
keywords = ["couchdb", "database"]

classifiers = [
    "Topic :: Utilities",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^2.7 | ^3.8 | ^3.7 | ^3.9"
requests = "^2.25"
pytest = "<=6.2"

[tool.poetry.dev-dependencies]
responses = "^0.10"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
